<?php

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural' => 'Posts',
                'icon' => 'voyager-news',
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-23 07:19:44',
                'updated_at' => '2018-02-23 07:19:44',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural' => 'Pages',
                'icon' => 'voyager-file-text',
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-23 07:19:44',
                'updated_at' => '2018-03-02 11:05:29',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-23 07:19:45',
                'updated_at' => '2018-02-23 07:19:45',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-23 07:19:45',
                'updated_at' => '2018-02-23 07:19:45',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-23 07:19:45',
                'updated_at' => '2018-02-23 07:19:45',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-23 07:19:45',
                'updated_at' => '2018-02-23 07:19:45',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => 'icon fas fa-cube',
                'model_name' => 'App\\Models\\Product',
                'policy_name' => NULL,
                'controller' => 'Back\\ProductsController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'created_at' => '2018-02-23 07:22:59',
                'updated_at' => '2018-03-02 07:36:49',
            ),
            7 => 
            array (
                'id' => 13,
                'name' => 'brands',
                'slug' => 'brands',
                'display_name_singular' => 'Brand',
                'display_name_plural' => 'Brands',
                'icon' => 'icon fas fa-industry',
                'model_name' => 'App\\Models\\Brand',
                'policy_name' => NULL,
                'controller' => 'Back\\BrandsController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'created_at' => '2018-02-26 03:38:03',
                'updated_at' => '2018-03-02 04:31:51',
            ),
            8 => 
            array (
                'id' => 18,
                'name' => 'product_categories',
                'slug' => 'product-categories',
                'display_name_singular' => 'Product Category',
                'display_name_plural' => 'Product Categories',
                'icon' => 'icon far fa-folder-open',
                'model_name' => 'App\\Models\\ProductCategory',
                'policy_name' => NULL,
                'controller' => 'Back\\ProductCategoriesController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'created_at' => '2018-02-26 07:57:57',
                'updated_at' => '2018-03-05 10:42:22',
            ),
            9 => 
            array (
                'id' => 19,
                'name' => 'bread_templates',
                'slug' => 'templates',
                'display_name_singular' => 'Template',
                'display_name_plural' => 'Templates',
                'icon' => 'voyager-news',
                'model_name' => 'Launcher\\BreadTemplates\\Models\\Template',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-26 13:24:53',
                'updated_at' => '2018-02-26 13:24:53',
            ),
            10 => 
            array (
                'id' => 20,
                'name' => 'trends',
                'slug' => 'trends',
                'display_name_singular' => 'Trend',
                'display_name_plural' => 'Trends',
                'icon' => 'icon fas fa-chart-line',
                'model_name' => 'App\\Models\\Trend',
                'policy_name' => NULL,
                'controller' => 'Back\\TrendsControler',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-27 04:10:06',
                'updated_at' => '2018-03-02 04:32:30',
            ),
            11 => 
            array (
                'id' => 23,
                'name' => 'slide_shows',
                'slug' => 'slide-shows',
                'display_name_singular' => 'Slide Show',
                'display_name_plural' => 'Slide Shows',
                'icon' => 'icon far fa-images',
                'model_name' => 'App\\Models\\SlideShow',
                'policy_name' => NULL,
                'controller' => 'Back\\SlideShowController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-27 04:32:02',
                'updated_at' => '2018-03-02 07:39:56',
            ),
            12 => 
            array (
                'id' => 24,
                'name' => 'banners',
                'slug' => 'banners',
                'display_name_singular' => 'Banner',
                'display_name_plural' => 'Banners',
                'icon' => 'icon far fa-image',
                'model_name' => 'App\\Models\\Banner',
                'policy_name' => NULL,
                'controller' => 'Back\\BannersController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-27 04:36:30',
                'updated_at' => '2018-03-02 07:37:47',
            ),
            13 => 
            array (
                'id' => 26,
                'name' => 'solutions',
                'slug' => 'solutions',
                'display_name_singular' => 'Solution',
                'display_name_plural' => 'Solutions',
                'icon' => 'icon far fa-file-alt',
                'model_name' => 'App\\Models\\Solution',
                'policy_name' => NULL,
                'controller' => 'Back\\SolutionsController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-27 04:56:43',
                'updated_at' => '2018-03-02 07:39:10',
            ),
            14 => 
            array (
                'id' => 27,
                'name' => 'vouchers',
                'slug' => 'vouchers',
                'display_name_singular' => 'Voucher',
                'display_name_plural' => 'Vouchers',
                'icon' => 'icon fas fa-ticket-alt',
                'model_name' => 'App\\Models\\Voucher',
                'policy_name' => NULL,
                'controller' => 'Back\\VouchersController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-02-27 04:58:36',
                'updated_at' => '2018-03-02 07:38:50',
            ),
            15 => 
            array (
                'id' => 29,
                'name' => 'stores',
                'slug' => 'stores',
                'display_name_singular' => 'Store',
                'display_name_plural' => 'Stores',
                'icon' => 'icon fa fa-building',
                'model_name' => 'App\\Models\\Store',
                'policy_name' => NULL,
                'controller' => 'Back\\StoresController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'created_at' => '2018-02-28 07:47:27',
                'updated_at' => '2018-03-01 08:40:35',
            ),
            16 => 
            array (
                'id' => 30,
                'name' => 'store_photos',
                'slug' => 'store-photos',
                'display_name_singular' => 'Store Photo',
                'display_name_plural' => 'Store Photos',
                'icon' => 'icon far fa-images',
                'model_name' => 'App\\Models\\StorePhoto',
                'policy_name' => NULL,
                'controller' => 'Back\\StorePhotosController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'created_at' => '2018-03-08 04:25:16',
                'updated_at' => '2018-03-08 13:38:18',
            ),
        ));
        
        
    }
}